const std = @import("std");
const sorvi = @import("sorvi");

pub fn build(b: *std.Build) void {
    const target = b.standardTargetOptions(.{});
    const optimize = b.standardOptimizeOption(.{});

    // fixup hack until sorvi repo becomes public
    // set this to true whenever these deps update
    // and then back to false once symlinks are updated
    if (false) {
        const zon = @import("build.zig.zon");
        inline for (.{ "sorvi_SDL3", "sorvi_physfs" }) |name| {
            const dep = @field(zon.dependencies, name);
            const path = b.graph.global_cache_root.join(b.allocator, &.{ "p", dep.hash }) catch @panic("OOM");
            const dir = std.fs.cwd().openDir(path, .{}) catch unreachable;
            dir.symLink(b.pathFromRoot("../sorvi"), "sorvi", .{ .is_directory = true }) catch {};
        }
        return;
    }

    const sorvi_dep = b.dependency("sorvi", .{
        .target = target,
        .optimize = optimize,
    });

    const frontend = sorvi_dep.artifact("sorvi-frontend");

    const sdl3_dep = b.dependency("sorvi_SDL3", .{
        .target = target,
        .optimize = optimize,
        .sdl2_compat = true,
    });

    const sdl2_dep = b.dependency("SDL2", .{
        .target = sorvi.resolveSorviTarget(b, target.query),
        .optimize = optimize,
    });

    const physfs_dep = b.dependency("sorvi_physfs", .{
        .target = target,
        .optimize = optimize,
    });

    const al_dep = b.dependency("openal", .{
        .target = sorvi.resolveSorviTarget(b, target.query),
        .optimize = optimize,
        .backend = .sdl2,
    });

    const vorbis_dep = b.dependency("libvorbis", .{
        .target = sorvi.resolveSorviTarget(b, target.query),
        .optimize = optimize,
    });

    const zlib_dep = b.dependency("zlib", .{
        .target = sorvi.resolveSorviTarget(b, target.query),
        .optimize = optimize,
    });

    const glm_dep = b.dependency("glm", .{});
    const fmt_dep = b.dependency("fmt", .{});

    const libsquirrel = b.addLibrary(.{
        .name = "squirrel",
        .linkage = .static,
        .root_module = b.createModule(.{
            .target = sorvi.resolveSorviTarget(b, target.query),
            .optimize = optimize,
            .link_libc = true,
            .link_libcpp = true,
            .sanitize_c = .off,
        }),
    });

    libsquirrel.installHeadersDirectory(b.path("external/simplesquirrel/libs/squirrel/include"), "", .{});
    libsquirrel.installHeadersDirectory(b.path("external/simplesquirrel/include"), "", .{});
    libsquirrel.root_module.addSystemIncludePath(b.path("external/simplesquirrel/include"));
    libsquirrel.root_module.addSystemIncludePath(b.path("external/simplesquirrel/libs/squirrel/include"));

    libsquirrel.root_module.addCSourceFiles(.{
        .files = &.{
            "args.cpp",
            "array.cpp",
            "binding.cpp",
            "class.cpp",
            "enum.cpp",
            "exceptions.cpp",
            "function.cpp",
            "instance.cpp",
            "object.cpp",
            "script.cpp",
            "table.cpp",
            "vm.cpp",
        },
        .root = b.path("external/simplesquirrel/source"),
    });

    libsquirrel.root_module.addCSourceFiles(.{
        .files = &.{
            "sqapi.cpp",
            "sqbaselib.cpp",
            "sqclass.cpp",
            "sqcompiler.cpp",
            "sqdebug.cpp",
            "sqfuncstate.cpp",
            "sqlexer.cpp",
            "sqmem.cpp",
            "sqobject.cpp",
            "sqstate.cpp",
            "sqtable.cpp",
            "sqvm.cpp",
        },
        .root = b.path("external/simplesquirrel/libs/squirrel/squirrel"),
    });

    libsquirrel.root_module.addCSourceFiles(.{
        .files = &.{
            "sqstdaux.cpp",
            "sqstdblob.cpp",
            "sqstdio.cpp",
            "sqstdmath.cpp",
            "sqstdrex.cpp",
            "sqstdstream.cpp",
            "sqstdstring.cpp",
            "sqstdsystem.cpp",
        },
        .root = b.path("external/simplesquirrel/libs/squirrel/sqstdlib"),
    });

    const libsexp = b.addLibrary(.{
        .name = "sexp",
        .linkage = .static,
        .root_module = b.createModule(.{
            .target = sorvi.resolveSorviTarget(b, target.query),
            .optimize = optimize,
            .link_libc = true,
            .link_libcpp = true,
        }),
    });

    libsexp.installHeadersDirectory(b.path("external/sexp-cpp/include"), "", .{});
    libsexp.root_module.addSystemIncludePath(b.path("external/sexp-cpp/include"));

    libsexp.root_module.addCSourceFiles(.{
        .files = &.{
            "float.cpp",
            "io.cpp",
            "lexer.cpp",
            "parser.cpp",
            "util.cpp",
            "value.cpp",
        },
        .root = b.path("external/sexp-cpp/src"),
    });

    var assets = b.addWriteFiles();
    _ = assets.addCopyDirectory(b.path("data"), "", .{});

    const supertux = sorvi.addSorviCore(b, .{
        .name = "supertux",
        .root_module = b.createModule(.{
            .target = target,
            .optimize = optimize,
            .link_libc = true,
            .link_libcpp = true,
            .sanitize_c = .off,
        }),
        .assets = assets,
    });
    supertux.root_module.addCSourceFiles(.{
        .flags = &.{
            "-DFMT_HEADER_ONLY",
            "-DGLM_ENABLE_EXPERIMENTAL",
        },
        .files = &.{
            "addon/addon.cpp",
            "addon/addon_manager.cpp",
            "addon/downloader.cpp",
            "addon/md5.cpp",
            "audio/dummy_sound_source.cpp",
            "audio/ogg_sound_file.cpp",
            "audio/openal_sound_source.cpp",
            "audio/sound_error.cpp",
            "audio/sound_file.cpp",
            "audio/sound_manager.cpp",
            "audio/stream_sound_source.cpp",
            "audio/wav_sound_file.cpp",
            "badguy/angrystone.cpp",
            "badguy/badguy.cpp",
            "badguy/boss.cpp",
            "badguy/bouncing_snowball.cpp",
            "badguy/captainsnowball.cpp",
            "badguy/corrupted_granito.cpp",
            "badguy/corrupted_granito_big.cpp",
            "badguy/crusher.cpp",
            "badguy/crystallo.cpp",
            "badguy/dart.cpp",
            "badguy/darttrap.cpp",
            "badguy/dispenser.cpp",
            "badguy/dive_mine.cpp",
            "badguy/fish_chasing.cpp",
            "badguy/fish_harmless.cpp",
            "badguy/fish_jumping.cpp",
            "badguy/fish_swimming.cpp",
            "badguy/flame.cpp",
            "badguy/flyingsnowball.cpp",
            "badguy/ghosttree.cpp",
            "badguy/ghosttree_attack.cpp",
            "badguy/ghoul.cpp",
            "badguy/goldbomb.cpp",
            "badguy/granito.cpp",
            "badguy/granito_big.cpp",
            "badguy/granito_giant.cpp",
            "badguy/haywire.cpp",
            "badguy/igel.cpp",
            "badguy/jumpy.cpp",
            "badguy/kamikazesnowball.cpp",
            "badguy/kugelblitz.cpp",
            "badguy/livefire.cpp",
            "badguy/mole.cpp",
            "badguy/mole_rock.cpp",
            "badguy/mrbomb.cpp",
            "badguy/mriceblock.cpp",
            "badguy/mrtree.cpp",
            "badguy/owl.cpp",
            "badguy/plant.cpp",
            "badguy/rcrystallo.cpp",
            "badguy/root.cpp",
            "badguy/root_sapling.cpp",
            "badguy/scrystallo.cpp",
            "badguy/short_fuse.cpp",
            "badguy/skydive.cpp",
            "badguy/smartball.cpp",
            "badguy/smartblock.cpp",
            "badguy/snail.cpp",
            "badguy/snowball.cpp",
            "badguy/snowman.cpp",
            "badguy/spiky.cpp",
            "badguy/sspiky.cpp",
            "badguy/stalactite.cpp",
            "badguy/stumpy.cpp",
            "badguy/tarantula.cpp",
            "badguy/toad.cpp",
            "badguy/totem.cpp",
            "badguy/treewillowisp.cpp",
            "badguy/viciousivy.cpp",
            "badguy/walking_badguy.cpp",
            "badguy/walking_candle.cpp",
            "badguy/walkingleaf.cpp",
            "badguy/willowisp.cpp",
            "badguy/yeti.cpp",
            "badguy/yeti_stalactite.cpp",
            "badguy/zeekling.cpp",
            "collision/collision.cpp",
            "collision/collision_movement_manager.cpp",
            "collision/collision_object.cpp",
            "collision/collision_system.cpp",
            "control/codecontroller.cpp",
            "control/controller.cpp",
            "control/game_controller_manager.cpp",
            "control/input_manager.cpp",
            "control/joystick_config.cpp",
            "control/joystick_manager.cpp",
            "control/keyboard_config.cpp",
            "control/keyboard_manager.cpp",
            "control/mobile_controller.cpp",
            "editor/bezier_marker.cpp",
            "editor/button_widget.cpp",
            "editor/editor.cpp",
            "editor/editor_comment.cpp",
            "editor/layer_icon.cpp",
            "editor/layers_widget.cpp",
            "editor/marker_object.cpp",
            "editor/node_marker.cpp",
            "editor/object_group.cpp",
            "editor/object_icon.cpp",
            "editor/object_info.cpp",
            "editor/object_menu.cpp",
            "editor/object_option.cpp",
            "editor/object_settings.cpp",
            "editor/overlay_widget.cpp",
            "editor/particle_editor.cpp",
            "editor/resize_marker.cpp",
            "editor/scroller_widget.cpp",
            "editor/tile_selection.cpp",
            "editor/tilebox.cpp",
            "editor/tip.cpp",
            "editor/tool_icon.cpp",
            "editor/toolbar_widget.cpp",
            "editor/toolbox_widget.cpp",
            "editor/widget.cpp",
            "gui/dialog.cpp",
            "gui/item_action.cpp",
            "gui/item_back.cpp",
            "gui/item_color.cpp",
            "gui/item_color_picker_2d.cpp",
            "gui/item_colorchannel_rgba.cpp",
            "gui/item_colordisplay.cpp",
            "gui/item_controlfield.cpp",
            "gui/item_floatfield.cpp",
            "gui/item_goto.cpp",
            "gui/item_hl.cpp",
            "gui/item_horizontalmenu.cpp",
            "gui/item_images.cpp",
            "gui/item_inactive.cpp",
            "gui/item_intfield.cpp",
            "gui/item_label.cpp",
            "gui/item_list.cpp",
            "gui/item_paths.cpp",
            "gui/item_script.cpp",
            "gui/item_script_line.cpp",
            "gui/item_string_array.cpp",
            "gui/item_stringselect.cpp",
            "gui/item_textfield.cpp",
            "gui/item_toggle.cpp",
            "gui/menu.cpp",
            "gui/menu_color.cpp",
            "gui/menu_filesystem.cpp",
            "gui/menu_item.cpp",
            "gui/menu_list.cpp",
            "gui/menu_manager.cpp",
            "gui/menu_object_select.cpp",
            "gui/menu_paths.cpp",
            "gui/menu_script.cpp",
            "gui/menu_string_array.cpp",
            "gui/menu_transition.cpp",
            "gui/mousecursor.cpp",
            "gui/notification.cpp",
            "interface/container.cpp",
            "interface/control.cpp",
            "interface/control_button.cpp",
            "interface/control_checkbox.cpp",
            "interface/control_enum.cpp",
            "interface/control_scrollbar.cpp",
            "interface/control_textbox.cpp",
            "interface/control_textbox_float.cpp",
            "interface/control_textbox_int.cpp",
            "interface/label.cpp",
            "main.cpp",
            "math/aatriangle.cpp",
            "math/anchor_point.cpp",
            "math/bezier.cpp",
            "math/easing.cpp",
            "math/random.cpp",
            "math/rect.cpp",
            "math/rectf.cpp",
            "math/size.cpp",
            "math/sizef.cpp",
            "object/ambient_light.cpp",
            "object/ambient_sound.cpp",
            "object/background.cpp",
            "object/bicycle_platform.cpp",
            "object/bigsnowball.cpp",
            "object/block.cpp",
            "object/bonus_block.cpp",
            "object/bouncy_coin.cpp",
            "object/brick.cpp",
            "object/bullet.cpp",
            "object/bumper.cpp",
            "object/camera.cpp",
            "object/candle.cpp",
            "object/circleplatform.cpp",
            "object/cloud_particle_system.cpp",
            "object/coin.cpp",
            "object/coin_explode.cpp",
            "object/coin_rain.cpp",
            "object/conveyor_belt.cpp",
            "object/custom_particle_system.cpp",
            "object/custom_particle_system_file.cpp",
            "object/decal.cpp",
            "object/display_effect.cpp",
            "object/draggable_region.cpp",
            "object/electrifier.cpp",
            "object/endsequence.cpp",
            "object/endsequence_fireworks.cpp",
            "object/endsequence_walk.cpp",
            "object/explosion.cpp",
            "object/fallblock.cpp",
            "object/falling_coin.cpp",
            "object/firefly.cpp",
            "object/fireworks.cpp",
            "object/floating_image.cpp",
            "object/floating_text.cpp",
            "object/flower.cpp",
            "object/ghost_particle_system.cpp",
            "object/gradient.cpp",
            "object/growup.cpp",
            "object/hurting_platform.cpp",
            "object/infoblock.cpp",
            "object/invisible_block.cpp",
            "object/invisible_wall.cpp",
            "object/ispy.cpp",
            "object/key.cpp",
            "object/lantern.cpp",
            "object/level_time.cpp",
            "object/light.cpp",
            "object/lit_object.cpp",
            "object/magicblock.cpp",
            "object/moving_sprite.cpp",
            "object/music_object.cpp",
            "object/oneup.cpp",
            "object/particle_zone.cpp",
            "object/particles.cpp",
            "object/particlesystem.cpp",
            "object/particlesystem_interactive.cpp",
            "object/path.cpp",
            "object/path_gameobject.cpp",
            "object/path_object.cpp",
            "object/path_walker.cpp",
            "object/platform.cpp",
            "object/player.cpp",
            "object/pneumatic_platform.cpp",
            "object/powerup.cpp",
            "object/pulsing_light.cpp",
            "object/pushbutton.cpp",
            "object/rain_particle_system.cpp",
            "object/rainsplash.cpp",
            "object/rock.cpp",
            "object/rublight.cpp",
            "object/rusty_trampoline.cpp",
            "object/scripted_object.cpp",
            "object/shard.cpp",
            "object/smoke_cloud.cpp",
            "object/snow_particle_system.cpp",
            "object/sound_object.cpp",
            "object/spawnpoint.cpp",
            "object/specialriser.cpp",
            "object/spotlight.cpp",
            "object/sprite_particle.cpp",
            "object/star.cpp",
            "object/sticky_object.cpp",
            "object/text_array_object.cpp",
            "object/text_object.cpp",
            "object/textscroller.cpp",
            "object/thunderstorm.cpp",
            "object/tilemap.cpp",
            "object/torch.cpp",
            "object/trampoline.cpp",
            "object/unstable_tile.cpp",
            "object/vertical_stripes.cpp",
            "object/water_drop.cpp",
            "object/weak_block.cpp",
            "object/wind.cpp",
            "physfs/ifile_stream.cpp",
            "physfs/ifile_streambuf.cpp",
            "physfs/ofile_stream.cpp",
            "physfs/ofile_streambuf.cpp",
            "physfs/physfs_file_system.cpp",
            "physfs/physfs_sdl.cpp",
            "physfs/util.cpp",
            "sdk/discord.cpp",
            "sdk/integration.cpp",
            "sprite/sprite.cpp",
            "sprite/sprite_data.cpp",
            "sprite/sprite_manager.cpp",
            "squirrel/serialize.cpp",
            "squirrel/squirrel_environment.cpp",
            "squirrel/squirrel_scheduler.cpp",
            "squirrel/squirrel_thread_queue.cpp",
            "squirrel/squirrel_util.cpp",
            "squirrel/squirrel_virtual_machine.cpp",
            "squirrel/supertux_api.cpp",
            "supertux/autotile.cpp",
            "supertux/autotile_parser.cpp",
            "supertux/colorscheme.cpp",
            "supertux/command_line_arguments.cpp",
            "supertux/console.cpp",
            "supertux/controller_hud.cpp",
            "supertux/d_scope.cpp",
            "supertux/debug.cpp",
            "supertux/direction.cpp",
            "supertux/error_handler.cpp",
            "supertux/fadetoblack.cpp",
            "supertux/flip_level_transformer.cpp",
            "supertux/game_manager.cpp",
            "supertux/game_object.cpp",
            "supertux/game_object_change.cpp",
            "supertux/game_object_factory.cpp",
            "supertux/game_object_iterator.cpp",
            "supertux/game_object_manager.cpp",
            "supertux/game_session.cpp",
            "supertux/gameconfig.cpp",
            "supertux/globals.cpp",
            "supertux/info_box.cpp",
            "supertux/info_box_line.cpp",
            "supertux/level.cpp",
            "supertux/level_parser.cpp",
            "supertux/level_transformer.cpp",
            "supertux/levelintro.cpp",
            "supertux/levelset.cpp",
            "supertux/levelset_screen.cpp",
            "supertux/main.cpp",
            "supertux/menu/addon_browse_menu.cpp",
            "supertux/menu/addon_file_install_menu.cpp",
            "supertux/menu/addon_menu.cpp",
            "supertux/menu/addon_preview_menu.cpp",
            "supertux/menu/cheat_apply_menu.cpp",
            "supertux/menu/cheat_menu.cpp",
            "supertux/menu/contrib_levelset_menu.cpp",
            "supertux/menu/contrib_menu.cpp",
            "supertux/menu/custom_menu_menu.cpp",
            "supertux/menu/debug_menu.cpp",
            "supertux/menu/download_dialog.cpp",
            "supertux/menu/editor_converters_menu.cpp",
            "supertux/menu/editor_delete_level_menu.cpp",
            "supertux/menu/editor_delete_levelset_menu.cpp",
            "supertux/menu/editor_level_menu.cpp",
            "supertux/menu/editor_level_select_menu.cpp",
            "supertux/menu/editor_levelset_menu.cpp",
            "supertux/menu/editor_levelset_select_menu.cpp",
            "supertux/menu/editor_menu.cpp",
            "supertux/menu/editor_new_levelset_menu.cpp",
            "supertux/menu/editor_objectgroup_menu.cpp",
            "supertux/menu/editor_save_as.cpp",
            "supertux/menu/editor_sector_menu.cpp",
            "supertux/menu/editor_sectors_menu.cpp",
            "supertux/menu/editor_settings.cpp",
            "supertux/menu/editor_temp_save_as.cpp",
            "supertux/menu/editor_temp_save_menu.cpp",
            "supertux/menu/editor_tilegroup_menu.cpp",
            "supertux/menu/game_menu.cpp",
            "supertux/menu/integrations_menu.cpp",
            "supertux/menu/joystick_menu.cpp",
            "supertux/menu/keyboard_menu.cpp",
            "supertux/menu/language_menu.cpp",
            "supertux/menu/main_menu.cpp",
            "supertux/menu/menu_storage.cpp",
            "supertux/menu/multiplayer_menu.cpp",
            "supertux/menu/multiplayer_player_menu.cpp",
            "supertux/menu/multiplayer_players_menu.cpp",
            "supertux/menu/options_menu.cpp",
            "supertux/menu/options_select_menu.cpp",
            "supertux/menu/particle_editor_menu.cpp",
            "supertux/menu/particle_editor_open.cpp",
            "supertux/menu/particle_editor_save_as.cpp",
            "supertux/menu/profile_menu.cpp",
            "supertux/menu/profile_name_menu.cpp",
            "supertux/menu/sorted_contrib_menu.cpp",
            "supertux/menu/video_system_menu.cpp",
            "supertux/menu/web_asset_menu.cpp",
            "supertux/menu/worldmap_cheat_apply_menu.cpp",
            "supertux/menu/worldmap_cheat_menu.cpp",
            "supertux/menu/worldmap_menu.cpp",
            "supertux/moving_object.cpp",
            "supertux/object_factory.cpp",
            "supertux/physic.cpp",
            "supertux/player_status.cpp",
            "supertux/player_status_hud.cpp",
            "supertux/profile.cpp",
            "supertux/profile_manager.cpp",
            "supertux/resources.cpp",
            "supertux/savegame.cpp",
            "supertux/screen_manager.cpp",
            "supertux/sector.cpp",
            "supertux/sector_base.cpp",
            "supertux/sector_parser.cpp",
            "supertux/sequence.cpp",
            "supertux/shrinkfade.cpp",
            "supertux/statistics.cpp",
            "supertux/textscroller_screen.cpp",
            "supertux/tile.cpp",
            "supertux/tile_manager.cpp",
            "supertux/tile_set.cpp",
            "supertux/tile_set_parser.cpp",
            "supertux/timer.cpp",
            "supertux/title_screen.cpp",
            "supertux/world.cpp",
            "trigger/climbable.cpp",
            "trigger/door.cpp",
            "trigger/scripttrigger.cpp",
            "trigger/secretarea_trigger.cpp",
            "trigger/sequence_trigger.cpp",
            "trigger/switch.cpp",
            "trigger/text_area.cpp",
            "trigger/trigger_base.cpp",
            "util/colorspace_oklab.cpp",
            "util/fade_helper.cpp",
            "util/file_system.cpp",
            "util/file_watcher.cpp",
            "util/gettext.cpp",
            "util/line_iterator.cpp",
            "util/log.cpp",
            "util/reader.cpp",
            "util/reader_collection.cpp",
            "util/reader_document.cpp",
            "util/reader_iterator.cpp",
            "util/reader_mapping.cpp",
            "util/reader_object.cpp",
            "util/script_manager.cpp",
            "util/string_util.cpp",
            "util/timelog.cpp",
            "util/uid.cpp",
            "util/uid_generator.cpp",
            "util/unique_name.cpp",
            "util/utf8_iterator.cpp",
            "util/writer.cpp",
            "video/bitmap_font.cpp",
            "video/blend.cpp",
            "video/canvas.cpp",
            "video/color.cpp",
            "video/compositor.cpp",
            "video/drawing_context.cpp",
            "video/drawing_target.cpp",
            "video/font.cpp",
            "video/null/null_painter.cpp",
            "video/null/null_renderer.cpp",
            "video/null/null_texture.cpp",
            "video/null/null_video_system.cpp",
            "video/sdl/sdl_painter.cpp",
            "video/sdl/sdl_screen_renderer.cpp",
            "video/sdl/sdl_texture.cpp",
            "video/sdl/sdl_texture_renderer.cpp",
            "video/sdl/sdl_video_system.cpp",
            "video/sdl_surface.cpp",
            "video/sampler.cpp",
            "video/surface.cpp",
            "video/surface_batch.cpp",
            "video/texture.cpp",
            "video/texture_manager.cpp",
            "video/ttf_font.cpp",
            "video/ttf_surface.cpp",
            "video/ttf_surface_manager.cpp",
            "video/sdlbase_video_system.cpp",
            "video/video_system.cpp",
            "video/viewport.cpp",
            "worldmap/camera.cpp",
            "worldmap/direction.cpp",
            "worldmap/level_tile.cpp",
            "worldmap/spawn_point.cpp",
            "worldmap/special_tile.cpp",
            "worldmap/sprite_change.cpp",
            "worldmap/teleporter.cpp",
            "worldmap/tux.cpp",
            "worldmap/world_select.cpp",
            "worldmap/worldmap.cpp",
            "worldmap/worldmap_object.cpp",
            "worldmap/worldmap_sector.cpp",
            "worldmap/worldmap_sector_parser.cpp",
            "worldmap/worldmap_state.cpp",
        },
        .root = b.path("src"),
    });
    supertux.root_module.addCSourceFiles(.{
        .files = &.{
            "obstack.c",
        },
        .root = b.path("external/obstack"),
    });
    supertux.root_module.addCSourceFiles(.{
        .files = &.{
            "src/dictionary.cpp",
            "src/dictionary_manager.cpp",
            "src/iconv.cpp",
            "src/language.cpp",
            "src/log.cpp",
            "src/plural_forms.cpp",
            "src/po_parser.cpp",
            "src/tinygettext.cpp",
            "src/unix_file_system.cpp",
        },
        .root = b.path("external/tinygettext"),
    });
    supertux.root_module.addCSourceFiles(.{
        .files = &.{
            "zip_manager.cpp",
        },
        .root = b.path("external/partio_zip"),
    });
    supertux.root_module.addCSourceFiles(.{
        .files = &.{
            "findlocale.c",
        },
        .root = b.path("external/findlocale"),
    });
    supertux.root_module.addIncludePath(b.path("src"));
    supertux.root_module.addSystemIncludePath(b.path("external/obstack"));
    supertux.root_module.addSystemIncludePath(b.path("external/tinygettext/include"));
    supertux.root_module.addSystemIncludePath(b.path("external/partio_zip"));
    supertux.root_module.addSystemIncludePath(b.path("external/findlocale"));
    supertux.root_module.addSystemIncludePath(b.path("src/sorvi"));
    supertux.root_module.addSystemIncludePath(glm_dep.path(""));
    supertux.root_module.addSystemIncludePath(fmt_dep.path("include"));
    const libSDL2 = sdl2_dep.artifact("SDL2");
    supertux.root_module.addSystemIncludePath(libSDL2.installed_headers.items[0].getSource().path(b, "SDL2"));
    libSDL2.root_module.linkLibrary(sdl3_dep.artifact("SDL3"));
    supertux.root_module.linkLibrary(libSDL2);
    supertux.root_module.linkLibrary(sdl2_dep.artifact("SDL_image"));
    supertux.root_module.linkLibrary(sdl2_dep.artifact("SDL_ttf"));
    supertux.root_module.linkLibrary(physfs_dep.artifact("physfs"));
    const libAL = al_dep.artifact("al");
    supertux.root_module.addSystemIncludePath(libAL.installed_headers.items[0].getSource().path(b, "AL"));
    libAL.root_module.addSystemIncludePath(libSDL2.installed_headers.items[0].getSource().path(b, "SDL2"));
    libAL.root_module.linkLibrary(libSDL2);
    supertux.root_module.linkLibrary(libAL);
    supertux.root_module.linkLibrary(vorbis_dep.artifact("vorbis"));
    supertux.root_module.linkLibrary(vorbis_dep.artifact("ogg"));
    supertux.root_module.linkLibrary(zlib_dep.artifact("z"));
    supertux.root_module.linkLibrary(libsquirrel);
    for (libsquirrel.installed_headers.items) |dir| supertux.root_module.addSystemIncludePath(dir.getSource());
    supertux.root_module.linkLibrary(libsexp);
    for (libsexp.installed_headers.items) |dir| supertux.root_module.addSystemIncludePath(dir.getSource());
    supertux.fixup(b);

    const step = b.step("run", "Run supertux in a reference frontend");
    step.dependOn(&sorvi.addRunSorviCore(b, frontend, supertux).step);
}
